'use client'

import Head from "next/head";
import Link from "next/link";
import { CircularProgress, CircularProgressLabel } from '@chakra-ui/react'

import {
  Table,
  TableBody,
  TableCaption,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from "@/components/ui/table"
import { Button } from "@/components/ui/button";




export default function Home() {
  const c: string[] = ["Active", "Active", "Request", "Requesting"];
  const request = () => {

  }

  return (
    <>
      <Head>
        <title> LauzHack 2023</title>
      </Head>
      <main className="flex justify-center min-h-screen flex-row w-full p-16">
        <Table>
          <TableHeader>
            <TableRow>
            {/* |status| Product | # total sev | # high | # med | # low | */}

              <TableHead>Status</TableHead>
              <TableHead>Product</TableHead>
              <TableHead># Severity </TableHead>
              <TableHead># High</TableHead>
              <TableHead># Medium</TableHead>
              <TableHead># Low</TableHead>
            </TableRow>
          </TableHeader>
          <TableBody>
            {c.map((c, index) => (
              <TableRow key={index}>
                <TableCell>
                  <Button variant="ghost" onClick={request} disabled={c!="Request"}>{
                    c == "Active" ? "Active" :
                      c == "Request" ? "Request" :
                        <CircularProgress isIndeterminate color='gray' size={30}/>
                  }</Button>
                </TableCell>
                <TableCell>Product Name</TableCell>
                <TableCell>42</TableCell>
                <TableCell className = "text-red-500">42</TableCell>
                <TableCell className = "text-yellow-500">42</TableCell>
                <TableCell className = "text-green-500">42</TableCell>
              </TableRow>
            ))}
          </TableBody>
        </Table>
      </main>  
    </>
  );


  // return (
  //   <>
  //     <Head>
  //       <title>Create T3 App</title>
  //       <meta name="description" content="Generated by create-t3-app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>
  //     <main className="flex justify-center min-h-screen flex-row w-full p-16">
  //       <div className="flex items-center justify-center flex-col h-full w-full p-4">
  //         <Input placeholder="Search" className="w-[70%]">
  //         </Input>

  //         {/* Tab makes its highlited */}
  //         <div className="flex flex-row items-center justify-center my-4 gap-[10%] w-[70%]">

  //           <FilterLocation></FilterLocation>


  //         </div>

  //         <Table>
  //           <TableHeader>
  //             <TableRow>
  //               <TableHead>Company</TableHead>
  //               <TableHead>Type</TableHead>
  //               <TableHead>Position</TableHead>
  //               <TableHead>Duration</TableHead>
  //               <TableHead>Salary</TableHead>
  //             </TableRow>
  //           </TableHeader>
  //           <TableBody>
  //             {jobs.map((job, index) => (
  //               <TableRow onClick={() => select(job)} key={index}>
  //                 <TableCell>{job.company}</TableCell>
  //                 <TableCell>{job.type}</TableCell>
  //                 <TableCell>{job.position}</TableCell>
  //                 <TableCell>{job.duration}</TableCell>
  //                 <TableCell>{job.salary}</TableCell>
  //               </TableRow>
  //             ))}
  //           </TableBody>
  //         </Table>
  //       </div>
  //       {
  //         selected != null ? (

  //           <Card className="w-full h-50 border-2 border-black">
  //             <Button variant="ghost" className="absolute translate-x-[-50px] hover:scale-150 hover:bg-transparent" onClick={() => select(null)}>
  //               <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" strokeWidth={1.5} stroke="currentColor" className="w-6 h-6">
  //                 <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
  //               </svg>

  //             </Button>
  //             <CardHeader>
  //               <CardTitle> {selected.position} @ {selected.company} </CardTitle>
  //               <CardDescription className="flex flex-row items-center">
  //                 <div>
  //                   <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-5 h-5">
  //                     <path stroke-linecap="round" stroke-linejoin="round" d="M14.25 7.756a4.5 4.5 0 100 8.488M7.5 10.5h5.25m-5.25 3h5.25M21 12a9 9 0 11-18 0 9 9 0 0118 0z" />
  //                   </svg>
  //                 </div>
  //                 <div> {selected.salary} </div>
  //                 <div className="w-[10%]"></div>
  //                 <div>
  //                   <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" className="w-5 h-5">
  //                     <path stroke-linecap="round" stroke-linejoin="round" d="M15 10.5a3 3 0 11-6 0 3 3 0 016 0z" />
  //                     <path stroke-linecap="round" stroke-linejoin="round" d="M19.5 10.5c0 7.142-7.5 11.25-7.5 11.25S4.5 17.642 4.5 10.5a7.5 7.5 0 1115 0z" />
  //                   </svg>
  //                 </div>
  //                 <div>
  //                   {selected.location.city}, {selected.location.country}
  //                 </div>
  //               </CardDescription>
  //             </CardHeader>
  //             <CardContent>
  //               <p>
  //                 "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."
  //               </p>
  //             </CardContent>

  //             <CardFooter>
  //               <Link href={selected.link} target="_blank">
  //                 <Button variant="outline" className="border-2 border-black">
  //                   Apply Now</Button>
  //               </Link>
  //             </CardFooter>
  //           </Card>
  //         ) : (
  //           <div></div>
  //         )
  //       }


  //     </main>
  //   </>
  // );
}
